### ISSUE TITLE
how to test changes to your code

### ISSUE THREAD

**Issue by ItamarShDev** [rliang/gnome-shell-extension-window-animations#2]
Hi
I want to play with the code and try to improve or help with bugs (like the maximized window bug i have submitted)
but when changing the code , in my case commenting 
```javascript 
 const extension = [
	new WindowFocusAnimation(), 
	new WindowMoveAnimation(),
	new WindowResizeAnimation()];
```
in both ``windows-animations.js`` and ``extension,js`` wont change a thing.\even after refreshing the shell

**Comment by rliang** [comment]
Hi,

Changing `extension.js` should work. That said if you comment that line everything should stop working.

Then again I haven't maintained this extension for a while (because of gnome shell misplacing windows as per your bug report) and using webpack was a bad move too.

**Comment by ItamarShDev** [comment]
OK.
 After changing the code, should it change the behavior on the fly?
Why using webpack was a bad move?

I am trying to learn this matter, and will be happy if you'll help

**Comment by rliang** [comment]
Hi again,

I managed to get an implementation working in [another extension I'm working on](https://github.com/rliang/gnome-shell-extension-tilingnome/blob/master/extension.js#L97).

Webpack was a bad move because it ended up introducing extra complexity for just some ES6 features (which already landed on GJS as of recently).

Also, it looks like gnome-shell 3.26 will introduce built-in animations for (un-)maximization, so most of this extension will become obsolete anyway. So I'll probably delete this one soon. But do tell if you still have another use-case in mind.

**Comment by ItamarShDev** [comment]
dont forget that Ubuntu users that use the LTS wont have Gnome 3.26 anytime soon 
In my case, my work laptop is on Ubuntu 16.04 and i wont update it anytime soon.
I'll check your other extension, and will be happy to help in whatever needed :)

**Comment by rliang** [comment]
Backported 👍

**Comment by ItamarShDev** [comment]
btw, the second extension doesnt work on gnome 3.20.4 for me. 
didnt wanted to open an issue there

**Comment by rliang** [comment]
Oh well, can you check if the logs say anything?

`journalctl -e /usr/bin/gnome-shell`

**Comment by rliang** [comment]
Oh nevermind, I see you meant the tiling extension. But no problem in opening an issue there.
